version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      DB_CONNECTION: 'mysql'
      DB_HOST: 'mysql'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    command: sh -c "composer install && php artisan migrate --force && php artisan db:seed && php artisan serve --host 0.0.0.0 --port 8000"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./productmanager
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
